name: transformer_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - scipy=1.11.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - jupyter=1.0.0
  - ipykernel=6.0.0
  - plotly=5.0.0
  - pip:
      - torch==2.1.0
      - torchvision==0.16.0
      - torchaudio==2.1.0
      - transformers==4.35.0
      - datasets==2.14.0
      - tokenizers==0.14.0
      - huggingface-hub==0.16.4
      - tensorboard==2.14.1
      - wandb==0.15.12
      - tqdm==4.66.1
      - accelerate==0.23.0
      - editdistance==0.6.2
      - psutil==5.9.5
      - pytest==7.4.0
      - pytest-cov==4.0.0
      - black==23.7.0
      - flake8==6.0.0
      - isort==5.12.0
      - mypy==0.991
      - nvidia-ml-py3==7.352.0 